import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChatProvider } from "@/context/chat/provider";
import { Sidebar } from "@/components/sidebar";
import { FiltersProvider } from "@/context/filter/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ChatProvider>
          <FiltersProvider>
            <div className="w-full h-full flex flex-row dark:bg-zinc-800">
              {children}
            </div>
          </FiltersProvider>
        </ChatProvider>
      </body>
    </html>
  );
}
